---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  
platforms:
- name: ubuntu-12.10
  driver_config:
    box: opscode-ubuntu-12.10
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.10_chef-provisionerless.box
    

suites:
- name: default
  run_list: ["recipe[doxygen::default]"]
  attributes: {}
